In [3]:
import numpy as np
array  = np.array([1,2,3,4,5])


reversed_array = array[::-1]
print (reversed_array)

import numpy as np
arr = np.array([[1,2,3],[2,4,5],[1,2,3]])
flattened_arr = arr.flatten()
print(flattened_arr) 

import numpy as np
arr = np.array([[1,2,3],[2,4,5],[1,2,3]])
flattened_arr = arr.ravel()
print(flattened_arr) 

import numpy as np

def compare_2d_array(arr1, arr2):
    arr1 = np.array(arr1)
    arr2 = np.array(arr2)

    elementwise_comparison = arr1 == arr2
    print("Element-wise comparison (True means equal):")
    print(elementwise_comparison)

array1 = np.array([1,2])
array2 = np.array([2, 3])
result=np.dot(array1,array2)
print(result)
print(array1)

print(array2)

print(np.cov(array1, array2))

8
[1 2]
[2 3]
[[0.5 0.5]
 [0.5 0.5]]


In [4]:
import numpy as np


array1 = np.array([4,5])
array2 = np.array([6,7])

result=np.dot(array1,array2)
print(result)
print(array1)
print(array1)

print(array2)

print(np.cov(array1, array2))

59
[4 5]
[4 5]
[6 7]
[[0.5 0.5]
 [0.5 0.5]]


In [5]:
import numpy as np


array1 = np.array([6,7,2])
array2 = np.array([4,5,1])

result=np.dot(array1,array2)
print(result)
print(array1)
print(array1)

print(array2)

print(np.cov(array1, array2))

61
[6 7 2]
[6 7 2]
[4 5 1]
[[7.         5.5       ]
 [5.5        4.33333333]]


In [6]:
x=np.array([[2,3,4],[3,2,9]])
y=np.array([[1,5,0],[5,10,3]])
a=np.inner(x,y)
b=np.outer(x,y)
c=np.cross(x,y)
print(a)
print(b)
print(c)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[-20   4   7]
 [-84  36  20]]


In [12]:
array=np.array([10,52,62,16,16,54,453])
res=np.sort(array)
indices=np.argsort(array)
reverse=res[::-1]
print(res)
print(indices)
print(res[0:4])
print(reverse[0:5])

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[453  62  54  52  16]


In [16]:
array=np.array([1.0,1.2,2.2,2.0,3.0,2.0])
integer = np.asarray(array, dtype=int)
froat = np.asarray(array, dtype=float)
print(integer)
print(froat)

[1 1 2 2 3 2]
[1.  1.2 2.2 2.  3.  2. ]


In [ ]:
import cv2
import numpy as np
def img_to_path(path):
    img_color=cv2.imread(path,cv2.IMREAD_COLOR)
    if img_coloris None:
        print("Error: img is not found")
        return
    img_gray=cv2.imread(path,cv2.IMREAD_GRAYSCALE)
    if np.array_equal(cv2.cvtColor(img_color,cv2.COLOR_BG2GRAY),img_gray):
        np.savetxt("image_array_grayscale.txt",img_gray,fmt='%d')
        print("COnverted")
        
    else:
        img_res=img_color.reshape(-1,3)
        np.savetxt("image_array_rgb.txt",img_reshaped,fmt='%d')
        print("sa